image: python:3.6

cache:
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip install -e .[dev,optional]

tests:
  script:
    - cd tests
    - python -m pytest --verbose
    - cd ..

pages:
  script:
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
