image: continuumio/miniconda3:latest

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda env create -f environment.yml
  - source activate imod
  - pip install -e .

tests:
  script:
    - cd tests
    - python -m unittest -v
    - cd ..

pages:
  script:
  - conda install sphinx
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
