image: python:3.6

cache:
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip install -e .[dev,optional]
  # switch to release when possible, see
  # https://github.com/Robpol86/sphinxcontrib-versioning/issues/59
  - pip install git+https://github.com/HTenkanen/sphinxcontrib-versioning
  - pip install git+https://github.com/jelmer/googleanalytics

tests:
  script:
    - cd tests
    - python -m pytest --verbose tests/test_regrid.py
    - export NUMBA_DISABLE_JIT=1
    - python -m pytest --verbose --cov=imod
    - cd ..
    - black --check . 

pages:
  script:
  - cd docs
  - make html
  - cd ..
  - sphinx-versioning build docs docs/_build/html
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
