image: condaforge/mambaforge

stages:
  - static code analysis
  - tests
  - build
  - publish

lint:
  stage: static code analysis
  script:
    # Avoid tox version with broken tox-conda.
    - mamba install "tox>=3.8.1, <4"
    - tox -e lint

mypy:
  stage: static code analysis
  variables:
    PYTHONHASHSEED: "0"
  script:
    - mamba env create -f imod-environment.yml
    - source activate imod
    - mamba install -y mypy mypy-gitlab-code-quality
    - mypy --no-error-summary | mypy-gitlab-code-quality > codequality.json
  artifacts:
    when: always
    reports:
      codequality: codequality.json
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

unit tests and coverage:
  stage: tests
  variables:
    NUMBA_DISABLE_JIT: "1"
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential curl
    - apt-get install libgl1-mesa-glx -y
    - mamba env create -f imod-environment.yml
    - mamba env update -f imod-environment-dev.yml --prefix /opt/conda/envs/imod
    - source activate imod
    # Do editable install as pytest expects that
    # https://github.com/scikit-hep/pyhf/issues/1456
    - pip install -e .
    # Run tests
    - cd imod/tests
    - python -m pytest --cache-clear --verbose --cov=imod --cov-config=.coveragerc
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    paths:
      - imod/tests/coverage.xml
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build documentation:
  stage: build
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential curl
    - apt-get install libgl1-mesa-glx -y
    - mamba env create -f imod-environment.yml
    - mamba env update -f imod-environment-dev.yml --prefix /opt/conda/envs/imod
    - source activate imod
    - pip install -e .
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/_build/html/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

publish documentation:
  stage: publish
  dependencies:
    - build documentation
  script:
    - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
