image: condaforge/miniforge3

stages:
  - static code analysis
  - build
  - publish

before_script:
  - conda install mamba
  
lint:
  stage: static code analysis
  script:
    # Avoid tox version with broken tox-conda.
    - mamba install "tox>=3.8.1, <4"
    - tox -e lint

mypy:
  stage: static code analysis
  variables:
    PYTHONHASHSEED: "0"
  script:
    - mamba env create -f imod-environment.yml
    - source activate imod
    - mamba install mypy mypy-gitlab-code-quality
    - mypy --no-error-summary | mypy-gitlab-code-quality > codequality.json
  artifacts:
    when: always
    reports:
      codequality: codequality.json
  allow_failure: true

# Run tests and create docs in the same stage. The docker image cannot (easily)
# be shared between stages, this avoids double setup of the environment.
build:
  stage: build
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential curl
    - apt-get install libgl1-mesa-glx -y
    - mamba env create -f imod-environment.yml
    - source activate imod
    # Do editable install as pytest expects that
    # https://github.com/scikit-hep/pyhf/issues/1456
    - pip install -e .
    # download mf6 binary and move it to the env's bin which is in the path
    # see https://gitlab.com/deltares/imod/imod-python/snippets/1893049
    - curl -O -L https://gitlab.com/deltares/imod/imod-python/uploads/a8ed27675150689c6acd425239531a5e/mf6.gz
    - gunzip mf6.gz
    - chmod +x mf6
    - mv mf6 /opt/conda/envs/imod/bin
    # Run tests
    - cd imod/tests
    - python -m pytest --cache-clear
    - python -m pytest --verbose test_regrid.py
    - python -m pytest --verbose test_visualize/test_visualize_pyvista.py
    - export NUMBA_DISABLE_JIT=1
    - python -m pytest --verbose --cov=imod --cov-config=.coveragerc
    - cd ../../docs
    - make html
    - cd ..
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    paths:
      - docs/_build/html/
      - imod/tests/coverage.xml 
    expire_in: 1 week

pages:
  stage: publish
  dependencies:
    - build
  script:
    - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
