image: continuumio/miniconda3:latest

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda update -n base conda
  - conda env create -f environment.yml
  - source activate imod
  - pip install -e .
  - pip install git+https://github.com/jelmer/googleanalytics
  # download mf6 binary and move it to the env's bin which is in the path
  # see https://gitlab.com/deltares/imod/imod-python/snippets/1893049
  - curl -O -L https://gitlab.com/deltares/imod/imod-python/uploads/404c0b0f1975939573ac8f2d4b154354/mf6.gz
  - gunzip mf6.gz
  - chmod +x mf6
  - mv mf6 /opt/conda/envs/imod/bin

tests:
  script:
    - cd tests
    - python -m pytest --verbose test_regrid.py
    - export NUMBA_DISABLE_JIT=1
    - python -m pytest --verbose --cov=imod
    - cd ..
    - black --check . 

pages:
  script:
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
