image: condaforge/miniforge3

stages:
  - lint
  - build
  - publish

before_script:
  - conda install mamba tox
  
lint:
  stage: lint
  script:
    - tox -e lint

build:
  stage: build
  script:
    - mamba install curl
    # download mf6 binary and add to path
    # see https://gitlab.com/deltares/imod/imod-python/snippets/1893049
    - curl -O -L https://gitlab.com/deltares/imod/imod-python/uploads/947a1e194a02ade1376d1111327db34d/mf6.gz
    - gunzip mf6.gz
    - chmod +x mf6
    - export PATH=$PATH:mf6
    # Runs tests and build docs with tox
    - tox -e build

publish:
  stage: publish
  script:
  - mv .tox/docs_out public/
  artifacts:
    paths:
    - public
  only:
  - master
