image: continuumio/miniconda3:latest

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda update -n base conda
  - conda env create -f environment.yml
  - source activate imod
  - pip install -e .
  - pip install git+https://github.com/jelmer/googleanalytics

tests:
  script:
    - cd tests
    - python -m pytest --verbose test_regrid.py
    - export NUMBA_DISABLE_JIT=1
    - python -m pytest --verbose --cov=imod
    - cd ..
    - black --check . 

pages:
  script:
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
