name: imod

channels:
  - conda-forge
  - defaults

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  - affine
  - black
  - cftime>=1
  - cytoolz
  - dask
  - geopandas
  - flopy
  - jinja2
  - matplotlib
  - nbstripout
  - numba
  - numpy
  - pandas
  - pytest
  - pytest-benchmark
  - pytest-cov
  - python>=3.6
  - rasterio>=1.0
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - toolz
  - twine
  - xarray>=0.11
