name: imod

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - numba
  - numpy
  - scipy
  - xarray>=0.11
  - cftime>=1
  - pandas
  - dask
  - cytoolz
  - toolz
  - rasterio>=1.0
  - geopandas
  - affine
  - jinja2
  - twine
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
  - nbstripout
  - black
