name: imod

channels:
  - conda-forge
  - defaults

dependencies:
  - affine
  - black
  - cftime>=1
  - cytoolz
  - dask
  - geopandas
  - jinja2
  - matplotlib
  - nbstripout
  - numba
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - python>=3.6
  - rasterio>=1.0
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - toolz
  - twine
  - xarray>=0.11
