name: imod

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - numba
  - numpy
  - xarray>=0.11
  - cftime
  - pandas
  - dask
  - cytoolz
  - toolz
  - rasterio>=1
  - affine
  - jinja2
  - twine
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - nbstripout
