name: imod

channels:
  - conda-forge
  - defaults

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.cfg
dependencies:
  - affine
  - black
  - bottleneck
  - cftime>=1
  - contextily>=1
  - cytoolz
  - dask
  - geopandas
  - graphviz
  - python-graphviz
  - flopy
  - jinja2
  - joblib
  - matplotlib
  - nbstripout
  - numba>=0.50
  - numpy
  - pandas
  - pooch
  - pip
  - pip:
    - declxml
    - meshzoo
    - pandamesh
    - xugrid
  - pydata-sphinx-theme
  - pygeos
  - pyproj
  - pytest
  - pytest-benchmark
  - pytest-cov
  - python>=3.7,<3.9
  - pyvista
  - rasterio>=1.0
  - scipy
  - setuptools_scm
  - sphinx
  - sphinx-gallery
  - toolz
  - tqdm
  - twine
  - vtk>=9.0
  - xarray>=0.15
  - zarr
