name: imod

channels:
  - conda-forge
  - defaults

dependencies:
  - affine
  - bottleneck
  - cftime>=1
  - contextily>=1
  - cytoolz
  - dask
  - geopandas
  - graphviz
  - python-graphviz
  - fastcore
  - flopy
  - jinja2
  - matplotlib
  - modflow6
  - netcdf4
  - numba>=0.50
  - numpy
  - pandas<2.0  # TODO: unpin when newer xarray on conda-forge
  - pooch
  - pip
  - pip:
      - pandamesh
  - pydata-sphinx-theme
  - pyproj
  - python=3.10
  - pyvista
  - rasterio>=1.0
  - rioxarray
  - scipy
  - setuptools_scm
  - scooby
  - shapely>=2.0
  - toolz
  - tomli>=1.1.0
  - tomli-w
  - tqdm
  - twine
  - vtk>=9.0
  - vtk * qt* # Select only qt builds
  - xarray>=0.15
  - xugrid>=0.6.4
  - zarr
