name: imod

channels:
  - conda-forge
  - defaults

dependencies:
  - affine
  - black
  - bottleneck
  - cftime>=1
  - contextily>=1
  - cytoolz
  - dask
  - geopandas
  - graphviz
  - python-graphviz
  - fastcore
  - flopy
  - hypothesis
  - jinja2
  - matplotlib
  - netcdf4
  - numba>=0.50
  - numpy
  - pandas<2.0  # TODO: unpin when newer xarray on conda-forge
  - pooch
  - pip
  - pip:
      - pandamesh
      - "git+https://github.com/Deltares/Ribasim.git#egg=ribasim&subdirectory=python/ribasim"
      - "git+https://github.com/Deltares/Ribasim.git#egg=ribasim_testmodels&subdirectory=python/ribasim_testmodels"
  - pydata-sphinx-theme
  - pyproj
  - pytest
  - pytest-benchmark
  - pytest-cases
  - pytest-cov
  - python=3.10
  - pyvista
  - rasterio>=1.0
  - rioxarray
  - scipy
  - setuptools_scm
  - scooby
  - shapely>=2.0
  - sphinx=5
  - sphinx-gallery
  - toolz
  - tomli>=1.1.0
  - tomli-w
  - tqdm
  - twine
  - vtk>=9.0
  - vtk * qt* # Select only qt builds
  - xarray>=0.15
  - xugrid>=0.3.0
  - zarr
